name: Continuous Integration for Mobile

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
  # push:
  #   branches:
  #     - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies in app
        run: cd ConnectAppMobile && npm install

      - name: Run tests
        run: cd ConnectAppMobile && npm run test

    
  build-android:
    needs: install-and-test
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: Install npm dependencies
        run: |
          cd ConnectAppMobile && npm install
      - name: Build Android Release
        run: |
          cd ConnectAppMobile && cd android && ./gradlew assembleRelease
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/